######################################################################
# Automatically generated by qmake (2.01a) Mon May 5 01:52:26 2008
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += /usr/lib/ruby/1.8/i486-linux/ /usr/include/smoke

# Input
SOURCES += expblur.cpp
