######################################################################
# Automatically generated by qmake (2.01a) Mon May 5 01:52:26 2008
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += expblur.cpp
